# Generated by Django 4.2.22 on 2025-08-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('schedule', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('resources', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='healthinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('usertype', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('bloodgroup', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=200)),
                ('instruction', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('DOCTORS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.doctors')),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='medicalhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=200)),
                ('medication', models.CharField(max_length=200)),
                ('allergies', models.CharField(max_length=200)),
                ('treatments', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.login'),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('DOCTORS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.doctors')),
                ('PATIENTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('invoice', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('paymentdate', models.DateField(blank=True, max_length=200, null=True)),
                ('insurance', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
            ],
        ),
    ]
